//
//  HouseListState.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import Foundation
import IdentifiedCollections

struct HouseListState: Equatable {
    var page: Int = 1
    var pageSize: Int = 50
    var rowStates: IdentifiedArray<UUID, HouseListRowState> = .init()
    var isLoading = false
    var allHousesLoaded = false
    var selection: Identified<HouseListRowState.ID, HouseDetailState>?
}
