//
//  HouseListView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct HouseListView: View {
    let store: Store<HouseListState, HouseListAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: HouseListView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            if viewStore.isInitialLoading {
                Color.clear
                    .frame(height: 0)
                    .onAppear {
                        viewStore.send(.refresh)
                    }
            }

            if viewStore.isLoading {
                ProgressView()
            } else {
                List(selection: viewStore.binding(get: { $0.selection }, send: HouseListView.Action.setSelection)) {
                    ForEachStore(
                        store.scope(
                            state: \.rowStates,
                            action: HouseListAction.row
                        )
                    ) { rowStore in
                        HouseListRowView(store: rowStore)
                    }
                }
                .onAppear {
                    viewStore.send(.onAppear)
                }
                .alert(
                    self.store.scope(state: { $0.alertState }),
                    dismiss: .alertDismissed
                )
                .refreshable {
                    await viewStore.send(.refresh, while: \.isLoading)
                }
                .navigationTitle("Houses")
            }
        }
    }
}
