//
//  HouseListReducer.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum HouseListModule {}

extension HouseListModule {
    static var reducer: Reducer<HouseListState, HouseListAction, HouseListEnvironment> {
        Reducer.combine(
            HouseListRowModule.reducer
            .forEach(
                state: \.rowStates,
                action: /HouseListAction.row,
                environment: {
                    .init(mainQueue: $0.mainQueue, fetchHouse: $0.fetchHouse)
                }
            ),
            Reducer<HouseListState, HouseListAction, HouseListEnvironment> { state, action, environment in
                switch action {
                case .onAppear:
                    return .init(value: .fetchHouses)
                case .refresh:
                    return .init(value: .fetchHouses)
                case .fetchHouses:
                    state.isLoading = true
                    return environment
                        .fetchHouses(state.page, state.pageSize)
                        .receive(on: environment.mainQueue())
                        .catchToEffect()
                        .map(HouseListAction.housesResponse)
                case let .housesResponse(.success(houses)):
                    state.allHousesLoaded = houses.count < state.pageSize
                    state.isLoading = false
                    state.rowStates = .init(uniqueElements: houses.map { HouseListRowState(id: UUID(), dataModel: $0) })
                case let .housesResponse(.failure(error)):
                    state.isLoading = false
                case .fetchNextHouses:
                    // TODO: reset page if failed?
                    guard !state.allHousesLoaded else {
                        return .none
                    }
                    state.page += 1
                    return .init(value: .fetchHouses)
                case let .nextHousesResponse(.success(houses)):
                    state.allHousesLoaded = houses.count < state.pageSize
                    state.isLoading = false
                    houses.map { HouseListRowState(id: UUID(), dataModel: $0) }
                        .forEach { state.rowStates.append($0) }
                case let .nextHousesResponse(.failure(error)):
                    state.isLoading = false
                case let .row(id, action):
                    switch action {
                    case let .houseResponse(id, .success(dataModel)):
                        state.selection = .init(.init(dataModel: dataModel), id: id)
                    default: ()
                    }
                }
                return .none
            }
        )
    }
}
