//
//  CategoryAction.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 16/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

enum CategoryAction: Equatable {
    case onAppear
    case houses(HouseListAction)
    case characters(CharacterListAction)
    case books(BookListAction)
}
