//
//  CategoryView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 16/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct CategoryView: View {
    let store: Store<CategoryState, CategoryAction>

    var body: some View {
        SwitchStore(store) {
            CaseLet(state: /CategoryState.houses, action: CategoryAction.houses) { houseListStore in
                HouseListView(store: houseListStore)
            }

            CaseLet(state: /CategoryState.characters, action: CategoryAction.characters) { characterListStore in
                CharacterListView(store: characterListStore)
            }

            CaseLet(state: /CategoryState.books, action: CategoryAction.books) { booksStore in
                BookListView(store: booksStore)
            }

            Default {
                Text("Not implemented")
            }
        }
    }
}
