//
//  AppView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 31.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct AppView: View {
    let store: Store<AppState, AppAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: AppView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            NavigationView {
                // Sidebar (first column)
                Sidebar(selection: viewStore.binding(get: { $0.selectedNavigationItem }, send: AppView.Action.setSelectedNavigationItem))
                    .frame(minWidth: 200, minHeight: 700)

                // Primary view (second column)
                PrimaryView(navigationItem: viewStore.binding(get: { $0.selectedNavigationItem }, send: AppView.Action.setSelectedNavigationItem))
                    .frame(minWidth: 300, minHeight: 700)

                // Detail view (third column)
                Text("No item selected")
            }
        }
    }
}
