//
//  HouseListReducer.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum HouseListModule {}

extension HouseListModule {
    static var reducer: Reducer<HouseListState, HouseListAction, HouseListEnvironment> {
        .combine(
            HouseListRowModule.reducer
                .forEach(
                    state: \.self,
                    action: /.self,
                    environment: {
                        $0
                    }
                )
                .optional()
                .pullback(
                    state: \.viewState.value,
                    action: /HouseListAction.row,
                    environment: {
                        .init(mainQueue: $0.mainQueue, fetchHouse: $0.fetchHouse)
                    }
                ),
            .init { state, action, environment in
                switch action {
                case .onAppear:
                    guard state.viewState == .loading() else {
                        return .none
                    }

                    return .init(value: .refresh)

                case .refresh:
                    return .init(value: .fetchHouses)

                case .fetchHouses:
                    state.viewState = .loading()

                    return environment
                        .fetchHouses(state.page, state.pageSize)
                        .receive(on: environment.mainQueue())
                        .catchToEffect(HouseListAction.housesResponse)

                case let .housesResponse(.success(houses)):
                    state.allHousesLoaded = houses.count < state.pageSize
                    state.viewState = .loaded(.init(uniqueElements: houses.map { HouseListRowState(id: $0.id.absoluteString, dataModel: $0) }))

                case let .housesResponse(.failure(error)):
                    state.viewState = .failure(error)

                case .fetchNextHouses:
                    // TODO: reset page if failed?
                    guard !state.allHousesLoaded else {
                        return .none
                    }

                    // TODO:
//                    if var lastRowState = state.rowStates.last {
//                        lastRowState.isLoading = true
//                        state.rowStates.updateOrAppend(lastRowState)
//                    }

                    state.page += 1

                    return environment
                        .fetchHouses(state.page, state.pageSize)
                        .receive(on: environment.mainQueue())
                        .catchToEffect(HouseListAction.nextHousesResponse)

                case let .nextHousesResponse(.success(houses)):
                    state.allHousesLoaded = houses.count < state.pageSize

                    // TODO:
//                    if var lastRowState = state.rowStates.last {
//                        lastRowState.isLoading = false
//                        state.rowStates.updateOrAppend(lastRowState)
//                    }

                    let newRows = houses.map { HouseListRowState(id: $0.id.absoluteString, dataModel: $0) }
                    state.viewState.value?.append(contentsOf: newRows)

                case let .nextHousesResponse(.failure(error)):
                    // TODO:
//                    if var lastRowState = state.rowStates.last {
//                        lastRowState.isLoading = false
//                        state.rowStates.updateOrAppend(lastRowState)
//                    }
                    return .init(value: .presentAlert(error: error))

                case let .row(id, action):
                    switch action {
                    case .onAppear:
                        guard let value = state.viewState.value else {
                            return .none
                        }
                        guard let rowState = value.first(where: { $0.id == id }) else {
                            return .none
                        }
                        guard let index = value.firstIndex(of: rowState) else {
                            return .none
                        }
                        guard index == value.endIndex - 1 else {
                            return .none
                        }
                        return .init(value: .fetchNextHouses)

                    default: ()
                    }

                case let .selectHouse(selectedHouse): ()
                    // TODO:
//                    guard let selectedRowState = state.rowStates.first(where: { $0.id == selectedHouse }), selectedRowState.houseDetailState != nil else {
//                        state.selection = selectedHouse
//                        return .none
//                    }
//                    var selection: HouseListRowState.ID?
//                    for rowState in state.rowStates {
//                        var updatedRowState = rowState
//                        updatedRowState.selected = rowState.id == selectedHouse
//                        state.rowStates.updateOrAppend(updatedRowState)
//
//                        if selection == nil, updatedRowState.selected, updatedRowState.houseDetailState != nil {
//                            selection = updatedRowState.id
//                        }
//                    }
//                    if let selection = selection {
//                        state.selection = selection
//                    }

                case let .presentAlert(error):
                    state.alertState = AlertState(title: TextState("Error"), message: TextState(error.localizedDescription))

                case .alertDismissed:
                    state.alertState = nil

                case let .setSelection(selection: .some(id)):
                    guard let rowState = state.viewState.value?.first(where: { $0.id == id }) else {
                        return .none
                    }
                    state.selection = .init(id: id, url: rowState.dataModel.url)

                case .setSelection(selection: .none):
                    state.selection = nil
                }

                return .none
            }
        )
    }
}
