//
//  HouseListState.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import Foundation
import IdentifiedCollections

struct HouseListState: Equatable {
    var page: Int = 1
    var pageSize: Int = 50
    var viewState: ViewState<IdentifiedArrayOf<HouseListRowState>, HouseListError> = .loading()
    var allHousesLoaded = false
    var selection: HouseDetailState?
    var alertState: AlertState<HouseListAction>?
}

extension HouseListState: Hashable {}
