//
//  HouseDetailView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct HouseDetailView: View {
    let store: Store<HouseDetailState, HouseDetailAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: HouseDetailView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            List {
                HouseFactsView(
                    name: viewStore.dataModel.name,
                    region: viewStore.dataModel.region,
                    coatOfArms: viewStore.dataModel.coatOfArms,
                    words: viewStore.dataModel.words,
                    currentLord: viewStore.dataModel.currentLord,
                    heir: viewStore.dataModel.heir,
                    overlord: viewStore.dataModel.overlord,
                    founded: viewStore.dataModel.founded,
                    founder: viewStore.dataModel.founder,
                    diedOut: viewStore.dataModel.diedOut
                )

                Section(header: Text("\(viewStore.dataModel.titles.count) Titles")) {
                    HouseTitlesView(titles: viewStore.dataModel.titles)
                }

                Section(header: Text("\(viewStore.dataModel.seats.count) Seats")) {
                    HouseSeatsView(seats: viewStore.dataModel.seats)
                }

                Section(header: Text("\(viewStore.dataModel.ancestralWeapons.count) Ancestral Weapons")) {
                    HouseAncestralWeaponsView(ancestralWeapons: viewStore.dataModel.ancestralWeapons)
                }

                Section(header: Text("\(viewStore.dataModel.cadetBranches.count) Cadet Branches")) {
                    HouseCadetBranchesView(cadetBranches: viewStore.dataModel.cadetBranches)
                }

                Section(header: Text("\(viewStore.dataModel.swornMembers.count) Sworn Members")) {
                    HouseSwornMembersView(swornMembers: viewStore.dataModel.swornMembers)
                }
            }
            .listStyle(.sidebar)
            .navigationTitle(Text(viewStore.dataModel.name))

        }
    }
}
