//
//  AppEnvironment.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 31.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import Foundation

struct AppEnvironment {
    var mainQueue: () -> AnySchedulerOf<DispatchQueue>
    var houseClient: HouseClient
    var characterClient: CharacterClient
}
