//
//  AppView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 31.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct AppView: View {
    let store: Store<AppState, AppAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: AppView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            NavigationSplitView {
                // Sidebar
                CategorySelection(category: viewStore.binding(get: \.category, send: AppView.Action.setSelectedCategory))
                    .frame(minWidth: 200, minHeight: 700)
            } content: {
                // Content view / second column
                IfLetStore(
                    store.scope(state: \.categoryList, action: AppAction.categoryList),
                    then: CategoryListView.init,
                    else: {
                        Text("No category selected")
                    }
                )
                .frame(minWidth: 300, maxWidth: 700, minHeight: 700)
            } detail: {
                NavigationStack {
                    WithViewStore(store) { viewStore in
                        if viewStore.selectedHouse != nil {
                            IfLetStore(
                                store.scope(state: \.selectedHouse, action: AppAction.houseDetail),
                                then: HouseDetailView.init,
                                else: {
                                    Text("No item selected")
                                }
                            )
                            .frame(minWidth: 500, maxWidth: 700, minHeight: 700)
                        } else if viewStore.selectedCharacter != nil {
                            IfLetStore(
                                store.scope(state: \.selectedCharacter, action: AppAction.characterDetail),
                                then: CharacterDetailView.init,
                                else: {
                                    Text("No item selected")
                                }
                            )
                            .frame(minWidth: 500, maxWidth: 700, minHeight: 700)
                        }
                    }
                }
            }
        }
    }
}
