//
//  BookDetailState.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Foundation

struct BookDetailState: Equatable {
    let url: URL
}

extension BookDetailState: Identifiable {
    var id: URL { url }
}

extension BookDetailState: Hashable {}
