//
//  BookDetailReducer.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum BookDetailModule {}

extension BookDetailModule {
    static var reducer: Reducer<BookDetailState, BookDetailAction, BookDetailEnvironment> {
        .init { state, action, environment in
            switch action {
            case .onAppear:
                return .init(value: .fetchBook)

            case .fetchBook:
                return environment.fetchBook(state.url)
                    .receive(on: environment.mainQueue())
                    .catchToEffect(BookDetailAction.bookResponse)

            case let .bookResponse(.success(book)):
                state.viewState = .loaded(book)

            case let .bookResponse(.failure(error)):
                state.viewState = .failure(error)

            default: ()
            }
            return .none
        }
    }
}
