//
//  BookDetailAction.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Foundation

enum BookDetailAction: Equatable {
    case onAppear
    case fetchBook
    case bookResponse(Result<BookDataModel, BookClientError>)
    case setSelectedCharacter(url: URL?)
}

extension BookDetailAction: Hashable {}
