//
//  CharacterDetailView.Action+feature.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 17/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension CharacterDetailView.Action {
    var feature: CharacterDetailAction {
        switch self {
        case .onAppear:
            return .onAppear
        case let .setSelectedCharacter(url):
            return .setSelectedCharacter(url: url)
        case let .setSelectedHouse(url):
            return .setSelectedHouse(url: url)
        }
    }
}
