//
//  CategoryListEnvironment.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 16/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import Foundation

struct CategoryListEnvironment {
    var mainQueue: () -> AnySchedulerOf<DispatchQueue>
    var fetchHouses: (_ page: Int, _ pageSize: Int) -> Effect<[HouseMetadataModel], HouseListError>
    var fetchHouse: (_ id: String, _ at: URL) -> Effect<HouseDataModel, HouseListError>
}
