//
//  HouseListRowView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct HouseListRowView: View {
    let store: Store<HouseListRowState, HouseListRowAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: HouseListRowView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            NavigationLink(
                destination: IfLetStore(
                    self.store.scope(
                        state: { $0.selection?.value },
                        action: HouseListRowAction.house
                    ),
                    then: HouseDetailView.init(store:)
                ),
                tag: viewStore.id,
                selection: viewStore.binding(
                    get: { $0.selection?.id },
                    send: HouseListRowView.Action.setNavigation(selection:)
                )
            ) {
                HStack {
                    Label(viewStore.dataModel.name, systemImage: "house")
                    
                    if viewStore.isLoading {
                        Spacer()
                        ProgressView()
                    }
                }
            }
            .alert(self.store.scope(state: { $0.alertState }), dismiss: .alertDismissed)
        }
    }
}
