//
//  HouseListRowAction.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Foundation

enum HouseListRowAction: Equatable {
    case onAppear
    case fetchHouse(id: UUID)
    case houseResponse(id: UUID, Result<HouseDataModel, HouseListError>)
    case setNavigation(selection: UUID?)
    case house(HouseDetailAction)
    case alertDismissed
}
