//
//  CharacterListView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 17/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct CharacterListView: View {
    let store: Store<CharacterListState, CharacterListAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: CharacterListView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            VStack {
                switch viewStore.viewState {
                case .loading(.none):
                    ProgressView()
                        .onAppear {
                            viewStore.send(.onAppear)
                        }
                case let .loaded(value), let .loading(.some(value)):
                    VStack {
                        List(selection: viewStore.binding(get: \.selection, send: CharacterListView.Action.setSelection)) {
                            ForEach(value) { character in
                                Label(character.name, systemImage: "person")
                            }
                        }
                        .listStyle(StyleConstants.houseListStyle)
                        .alert(
                            store.scope(state: \.alertState),
                            dismiss: .alertDismissed
                        )
                        .refreshable {
                            await viewStore.send(.refresh, while: \.viewState.isLoading)
                        }

                        if case ViewState.loading = viewStore.viewState {
                            ProgressView()
                        }
                    }
                case let .failure(error):
                    Text(error.localizedDescription)
                }
            }
            .navigationTitle("Characters")
        }
    }
}
