//
//  CharacterListReducer.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 17/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum CharacterListModule {}

extension CharacterListModule {
    static var reducer: Reducer<CharacterListState, CharacterListAction, CharacterListEnvironment> {
        .init { state, action, environment in
            return .none
        }
    }
}