//
//  CharacterListView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 17/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct CharacterListView: View {
    let store: Store<CharacterListState, CharacterListAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: CharacterListView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            Text("Character list here")
        }
    }
}
