//
//  HouseDetailView.Action+feature.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension HouseDetailView.Action {
    var feature: HouseDetailAction {
        switch self {
        case .onAppear:
            return .onAppear
        case let .setSelectedCharacter(url):
            return .setSelectedCharacter(url: url)
        case let .setSelectedHouse(url):
            return .setSelectedHouse(url: url)
        }
    }
}
