//
//  HouseDetailAction.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Foundation

enum HouseDetailAction: Equatable {
    case onAppear
    case fetchHouse
    case houseResponse(Result<HouseDataModel, HouseListError>)
    case setSelectedCharacter(url: URL?)
    case setSelectedHouse(url: URL?)
}

extension HouseDetailAction: Hashable {}
