//
//  HouseDetailAction.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

enum HouseDetailAction: Equatable {
    case onAppear
    case fetchHouse
    case houseResponse(Result<HouseDataModel, HouseListError>)
}

extension HouseDetailAction: Hashable {}
