//
//  BookListView+Action.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension BookListView {
    enum Action: Equatable {
        case onAppear
        case refresh
        case setSelection(selection: BookMetadataModel.ID?)
        case onDisappear
    }
}
