//
//  BookListReducer.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum BookListModule {}

extension BookListModule {
    static var reducer: Reducer<BookListState, BookListAction, BookListEnvironment> {
        .init { state, action, environment in
            return .none
        }
    }
}