//
//  BookListAction.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

enum BookListAction: Equatable {
    case onAppear
    case refresh
    case fetchBooks
    case booksResponse(Result<[BookMetadataModel], BookClientError>)
    case setSelection(selection: BookMetadataModel.ID?)
    case alertDismissed
    case onDisappear
}

extension BookListAction: Hashable {}
