//
//  BookListState.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29/07/2022.
//  Copyright © 2022 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import IdentifiedCollections

struct BookListState: Equatable {
    var page: Int = 1
    var pageSize: Int = 50
    var viewState: ViewState<IdentifiedArrayOf<BookMetadataModel>, BookClientError> = .loading()
    var selection: BookDetailState?
    var alertState: AlertState<BookListAction>?
}

extension BookListState: Hashable {}
