//
//  HouseListRowView.Action+feature.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

extension HouseListRowView.Action {
    var feature: HouseListRowAction {
        switch self {
        case HouseListRowView.Action.onAppear:
            return HouseListRowAction.onAppear
        case let HouseListRowView.Action.setSelected(selected):
            return HouseListRowAction.setSelected(selected: selected)
        }
    }
}
