//
//  HouseListRowView.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture
import SwiftUI

struct HouseListRowView: View {
    let store: Store<HouseListRowState, HouseListRowAction>

    var body: some View {
        WithViewStore(
            store.scope(
                state: { $0.view },
                action: { (viewAction: HouseListRowView.Action) in
                    viewAction.feature
                }
            )
        ) { viewStore in
            Label(viewStore.dataModel.name, systemImage: "house")
                .onAppear {
                    viewStore.send(.onAppear)
                }
        }
    }
}
