//
//  HouseListRowReducer.swift
//  Game-of-Thrones-SwiftUI
//
//  Created Christian Elies on 29.08.21.
//  Copyright © 2021 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import ComposableArchitecture

enum HouseListRowModule {}

extension HouseListRowModule {
    static var reducer: Reducer<HouseListRowState, HouseListRowAction, HouseListRowEnvironment> {
        Reducer<HouseListRowState, HouseListRowAction, HouseListRowEnvironment> { state, action, environment in
            return .none
        }
    }
}
